version: '3.4'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/project
    working_dir: /project
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    command:
      >
        sh -i -c -e
        "
        yarn install;
        yarn start:dev;
        "
  ruby:
    build:
      context: .
      dockerfile: tools/docker/ruby/Dockerfile
    volumes:
      - .:/project
      - ~/.ssh:/root/.ssh:ro
    working_dir: /project
    command:
      >
        sh -i -c -e
        "
        bundle install;
        "
